logging:
  level:
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN

#-----------------------------------------------
Spring:
  application:
    name: gateway
  #配置redis连接----------------------------------------------------------
  redis:
    database: 0
    host: 192.168.1.157
    port: 6379
    password: 123456
    #springboot2.0以上的版本默认使用的是lettuce redis客户端，如果想使用jedis客户端，则需把lettuce依赖进行排除以及手动引入jedis依赖
    lettuce:
      pool:
        max-active: 20  #连接池最大连接数
        max-wait: -1   #最大阻塞时间，-1没限制
        max-idle: 10  #最大空闲连接
        min-idle: 0  #最小空闲连接
    timeout: 3000  #超时
  #-----------------------------------------------------------------------
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.157:8848
    gateway:
      discovery:
        locator:
          enabled: true  #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true  #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
      routes:
        -id: user  #自定义id,无意义但不能重复，最好跟服务名保持一致
        uri: lb://user  # 注册中心中的服务
        predicates:
          - Path=/user/** # 转发该路径
        filters:
          #内置局部过滤器，必须加上StripPrefix=1，否则访问服务时会带上user
          - StripPrefix=1

      # 经过gateWay网关时，需要在网关统一配置跨域请求，全部通过
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
    stream:
      # Binding配置项,对应Map<String,BindingProperties>,order-output为Key,是Binding的名称
      # 自定义且可以定义多个,分为Input和Output两种配置,但在配置项中并不会体现出来,在@Input和@Output注解中体现
      bindings:
        log-output:
          # rocketmq 的topic
          destination: LOG-TOPIC-01
          # 消息内容格式
          content-type: application/json
      # SpringCloudStream RocketMQ配置项
      rocketmq:
        binder:
          # rocketmq 的nameserver地址
          name-server: 192.168.1.157:9876
        bindings:
          log-output:
            # producer配置项,对应RocketMQProducerProperties 类
            producer:
              # 生产者分组
              group: log-dev
              # 是否同步发送消息,默认为false异步
              sync: true

# 自定义配置
custom:
  # 是否在数据库记录访问日志
  insertAccessLog: true
  # 是否在控制台打印访问日志
  printAccessLog: false
  # token 过期时间(秒)  2小时
  tokenOutTime: 7200